// Generated by Wrangler by running `wrangler types`

interface Env {
	CHARACTERS: DurableObjectNamespace<import('./src/Character').Character>;
	ENCOUNTERS: DurableObjectNamespace<import('./src/Encounter').Encounter>;
	ENCOUNTER_IMAGES: R2Bucket;
	AI: Ai;
	GENERATE_IMAGE_WORKFLOW: Workflow;
	CHARACTER_IMAGES: R2Bucket;
}
