// Generated by Wrangler by running `wrangler types`

interface Env {
	CHARACTERS: DurableObjectNamespace<import("./src/index").Character>;
	ENCOUNTERS: DurableObjectNamespace<import("./src/index").Encounter>;
	AI: Ai;
}
